<#
  Name:             Start Companion Apps
  Description:      Starts the tools a game needs when it launches and closes them when it exits.
  Author:           TrayTrigger
  Version:          2.1
  Phase:            both
  Needs admin:      no
  Dependencies:     the programs you list
  Script Arguments: full paths of the programs to start, each in double quotes,
                    and "force" to end any that don't close when asked

  DO NOT EDIT THIS FILE. It is TrayTrigger's copy, not yours. Every time
  TrayTrigger starts it compares this file with the copy inside it and
  replaces it if they differ, which is how corrections reach you. An edit of
  yours is therefore undone at the very next start, not only when you update
  TrayTrigger. It is not thrown away: your version is renamed alongside, as
  this file's name with ".previous" on the end, and left alone after that.

  To make it yours properly: Edit Game > New script..., or copy this file
  under another name first - a file TrayTrigger did not put here is never
  touched. Settings that vary by PC belong in Edit Game > Script Arguments.

  WHY
    Sim racers start SimHub and Crew Chief, flight simmers start TrackIR,
    PlayStation controller owners start DS4Windows. Starting them by hand
    every time is tedious, and forgetting to close them afterwards leaves
    them running all day. This script does it for the games you choose it
    for, so SimHub starts with your racing games and not with the rest.

  FOR EVERY GAME, USE TOOLS INSTEAD
    To start a program with every game, add it on the Tools page and tick
    "Start when I launch a game" and "Close it when the game exits" in Edit
    Tool. Tools also handle programs that run as Administrator, like MSI
    Afterburner, and close what they start in the background, like RTSS.

  SET IT UP
    1. Find each program's full path: right-click its shortcut, choose Open
       file location, and copy the path from Explorer's address bar.
    2. In Edit Game, choose this file as the pre-launch script, tick "Use the
       same script for pre-launch and post-exit", and put the paths in Script
       Arguments, each in double quotes:
         "C:\Program Files (x86)\SimHub\SimHubWPF.exe" "C:\Program Files (x86)\Britton IT Ltd\CrewChiefV4\CrewChiefV4.exe"
       A program that needs extra options, such as a profile or "start
       minimized", goes in the $Companions list below instead - in a copy
       of this file under another name, since TrayTrigger replaces this one.
    3. Some programs ignore a request to close. They are left running and
       the script says which. Add "force" anywhere in Script Arguments to
       end those instead.
    4. Press Test next to the pre-launch box: the programs start. Press Test
       next to the post-exit box: they close.

  HOW IT WORKS
    prelaunch  Starts each program that isn't already running and notes the
               time and its path in your TEMP folder. A program you had
               already opened yourself is left alone.
    postexit   Closes only what this script started: every process from those
               paths that started after the note was written. It asks each
               one to close, the way Windows does when you sign out, which
               reaches tray programs too. After a few seconds anything still
               running is left alone, or ended if Script Arguments says
               "force".

  GOOD TO KNOW
    Without "force", a program that ignores the request keeps running until
    you close it. With "force", a program that is ended loses anything it
    hadn't saved; most companion tools save their settings as you change
    them, so that is usually fine.
    A program that runs as Administrator can't be closed from a normal
    script. The script says so, and it is left for you to close; or use
    Tools, which can close it.
    A program that starts through a separate launcher exe, which then starts
    the real program, can't be followed. List the real program's exe instead.

  MAKE IT YOURS
    Copy this file once per kind of game, for example "Sim Racing Apps.ps1"
    and "Flight Sim Apps.ps1", each with its own $Companions list. Then the
    Script Arguments box stays empty, or holds just "force".
#>
param(
    [string]$Phase,
    [string]$GameName,
    [string]$GameExe,
    [string]$GameId,
    [string]$Playtime,
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$ScriptArgs
)

# ---- Change these ------------------------------------------------------------

# Programs to start for every game that uses this file, with optional
# arguments. Paths from Script Arguments are added to this list. Remove the #
# in front of a line to use it.
$Companions = @(
    # @{ Path = 'C:\Program Files (x86)\NaturalPoint\TrackIR5\TrackIR5.exe'; Arguments = '' }
    # @{ Path = 'C:\Tools\DS4Windows\DS4Windows.exe'; Arguments = '-m' }
)

# How the programs' windows open: Normal, Minimized or Hidden.
$WindowStyle = 'Minimized'

# How long programs get to close on their own.
$GraceSeconds = 5

# ------------------------------------------------------------------------------

# The note that carries what was started from the pre-launch run to the
# post-exit run. Named after the game ID, so games don't mix up notes.
$note = Join-Path $env:TEMP "TrayTrigger-CompanionApps-$GameId.txt"

# "force" is a switch; every other word in Script Arguments is a path.
$force = $false
$paths = @()
foreach ($arg in $ScriptArgs) {
    if ($arg -eq 'force') { $force = $true }
    elseif ($arg) { $paths += $arg }
}

switch ($Phase) {
    'prelaunch' {
        $list = @($Companions)
        foreach ($path in $paths) { $list += @{ Path = $path; Arguments = '' } }
        if ($list.Count -eq 0) {
            Write-Output 'No programs listed. Put their paths in Edit Game > Script Arguments. To hard-code them in $Companions instead, copy this file under another name first - TrayTrigger replaces this one.'
            exit 0
        }

        $started = @()
        $startedNames = @()
        $alreadyRunning = @()
        $missing = @()
        foreach ($companion in $list) {
            # %ProgramFiles% and similar shortcuts are allowed in paths.
            $path = [Environment]::ExpandEnvironmentVariables($companion.Path)
            $name = [IO.Path]::GetFileNameWithoutExtension($path)

            if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
                Write-Output "Not found: $path"
                $missing += $name
                continue
            }

            # Already running from that path? Then you opened it yourself, and
            # this script won't close it later either.
            $already = Get-Process -Name $name -ErrorAction SilentlyContinue |
                Where-Object { $_.Path -eq $path }
            if ($already) {
                Write-Output "$name is already running. Leaving it alone."
                $alreadyRunning += $name
                continue
            }

            # Note the time just before starting, to recognise the process later.
            $startedAt = Get-Date

            $startArgs = @{
                FilePath         = $path
                # Many programs look for their own files next to the exe.
                WorkingDirectory = Split-Path -Parent $path
                WindowStyle      = $WindowStyle
            }
            if ($companion.Arguments) { $startArgs.ArgumentList = $companion.Arguments }
            Start-Process @startArgs

            Write-Output "Started $name."
            $started += '{0}|{1}' -f $startedAt.ToString('o'), $path
            $startedNames += $name
        }

        if ($started.Count -gt 0) {
            Set-Content -LiteralPath $note -Value $started
        }

        # One line for the player: a "TT:" line goes on the game's Played row in
        # Activity & History and into the launch popup. The rest is for the log.
        $summary = @()
        if ($startedNames.Count -gt 0) { $summary += "started $($startedNames -join ', ')" }
        if ($alreadyRunning.Count -gt 0) { $summary += "$($alreadyRunning -join ', ') already running" }
        if ($missing.Count -gt 0) { $summary += "not found: $($missing -join ', ')" }
        Write-Output "TT: $($summary -join '; ')"
    }

    'postexit' {
        if (-not (Test-Path -LiteralPath $note)) {
            Write-Output 'This script did not start anything. Nothing to close.'
            Write-Output 'TT: nothing to close'
            exit 0
        }
        $lines = @(Get-Content -LiteralPath $note)
        Remove-Item -LiteralPath $note -Force

        # Find the processes this script started: same exe path, started after
        # the time in the note. Anything else from that exe is yours, not ours.
        $targets = @()
        foreach ($line in $lines) {
            $time, $path = $line -split '\|', 2
            $startedAt = [datetime]::Parse($time, $null, [Globalization.DateTimeStyles]::RoundtripKind)
            $name = [IO.Path]::GetFileNameWithoutExtension($path)

            $running = @(Get-Process -Name $name -ErrorAction SilentlyContinue)
            $mine = @($running | Where-Object {
                try { $_.Path -eq $path -and $_.StartTime -ge $startedAt.AddSeconds(-1) } catch { $false }
            })
            if ($mine.Count -eq 0) {
                # A copy running as Administrator hides its path from a normal
                # script, so it can't be told apart, let alone closed.
                if ($running | Where-Object { -not $_.Path }) {
                    Write-Output "$name is running as Administrator, which this script can't close. Close it yourself, or add it on the Tools page, which can."
                }
                else {
                    Write-Output "$name has already closed."
                }
                continue
            }
            $targets += [pscustomobject]@{ Name = $name; Processes = $mine }
        }

        if ($targets.Count -eq 0) {
            Write-Output 'TT: everything this script started had closed already'
            exit 0
        }

        # Ask each one to close. taskkill without /F sends the same close message
        # Windows sends when you sign out, which reaches a tray program's hidden
        # window too. It fails at once for a program with no window at all.
        $taskkill = Join-Path $env:WINDIR 'System32\taskkill.exe'
        $asked = $false
        foreach ($target in $targets) {
            foreach ($process in $target.Processes) {
                & $taskkill /PID $process.Id 2>&1 | Out-Null
                if ($LASTEXITCODE -eq 0) { $asked = $true }
            }
        }
        if ($asked) {
            $targets.Processes | Wait-Process -Timeout $GraceSeconds -ErrorAction SilentlyContinue
        }

        $closedNames = @()
        $leftRunning = @()
        foreach ($target in $targets) {
            $left = @($target.Processes | Where-Object { -not $_.HasExited })
            if ($left.Count -eq 0) {
                Write-Output "Closed $($target.Name)."
                $closedNames += $target.Name
            }
            elseif ($force) {
                $left | Stop-Process -Force -ErrorAction SilentlyContinue
                Write-Output "Ended $($target.Name)."
                $closedNames += $target.Name
            }
            else {
                Write-Output "$($target.Name) didn't close when asked, so it was left running. Add force to Script Arguments to end it."
                $leftRunning += $target.Name
            }
        }

        $summary = @()
        if ($closedNames.Count -gt 0) { $summary += "closed $($closedNames -join ', ')" }
        if ($leftRunning.Count -gt 0) { $summary += "$($leftRunning -join ', ') wouldn't close" }
        Write-Output "TT: $($summary -join '; ')"
    }

    default {
        Write-Output "Unknown phase '$Phase'."
        exit 1
    }
}

exit 0
