<#
  Name:             Close Background Apps
  Description:      Closes background apps before a game and reopens them after; run as
                    Administrator, it also pauses Windows Update for the game.
  Author:           TrayTrigger
  Version:          2.0
  Phase:            both
  Needs admin:      no (yes to pause Windows Update)
  Dependencies:     none
  Script Arguments: "recommended" for the recommended list, and/or process names
                    to close, separated by spaces. Empty does nothing.

  DO NOT EDIT THIS FILE. It is TrayTrigger's copy, not yours. Every time
  TrayTrigger starts it compares this file with the copy inside it and
  replaces it if they differ, which is how corrections reach you. An edit of
  yours is therefore undone at the very next start, not only when you update
  TrayTrigger. It is not thrown away: your version is renamed alongside, as
  this file's name with ".previous" on the end, and left alone after that.

  To make it yours properly: Edit Game > New script..., or copy this file
  under another name first - a file TrayTrigger did not put here is never
  touched. Settings that vary by PC belong in Edit Game > Script Arguments.

  WHY
    Cloud sync, chat and launcher apps keep working in the background:
    uploading, downloading, indexing, popping up notifications. Windows Update
    downloading mid-game is one of the most common causes of stutter. Closing
    them for the length of a game frees CPU, disk and bandwidth. This script
    brings back exactly what it closed or paused when you are done, and says
    what it did. It does not "clean" memory or score your PC: those do nothing
    for a game.

  SET IT UP
    1. In Edit Game, choose this file as the pre-launch script and tick "Use
       the same script for pre-launch and post-exit".
    2. In Script Arguments, type "recommended" to close the recommended list:
         OneDrive, Dropbox, Google Drive, Adobe Creative Cloud, Microsoft
         Teams and Slack
       Or type the process names you want closed instead, for example:
         OneDrive Spotify
       Or both, to close the list and yours:
         recommended Spotify
       With Script Arguments empty the script does nothing at all.
       Find a process name in Task Manager > Details, without ".exe". Put a
       name that contains spaces in double quotes.
    3. To pause Windows Update and Delivery Optimization while you play, tick
       "Run scripts as Administrator" too (Script Arguments must name something,
       as above). Windows asks for permission before the game starts and again
       after it closes.
    4. Press Test next to the pre-launch box: the apps close. Press Test next
       to the post-exit box: they come back.

  OTHERS PEOPLE CLOSE, AND WHY THEY AREN'T ON THE LIST
    Browsers (chrome, msedge, firefox)   can lose tabs or a half-typed form
    Discord (Discord)                    you drop out of voice chat
    Mouse and keyboard software          your DPI, macros and lighting stop
      (lghub, iCUE, RazerAppEngine)
    Name them yourself if that's fine for you.

  HOW IT WORKS
    prelaunch  For each name that is running, remembers the program's full
               path and asks its window to close. Anything still running a
               few seconds later is ended. As Administrator, stops the
               Windows Update and Delivery Optimization services if they are
               running. What was closed and stopped goes into a note in your
               TEMP folder.
    postexit   Starts each remembered program again, unless it is already
               running, starts the services it stopped, and deletes the note.

  GOOD TO KNOW
    Apps that live only in the tray have no window to ask, so they are ended
    straight away. That is fine for sync and chat apps. Don't list an editor
    or anything else that could be holding unsaved work.
    A program running as Administrator can't be closed from a normal script,
    so it is skipped.
    Restarted apps start the way they do from their exe, which may open their
    window instead of starting in the tray. Run as Administrator, the script
    still reopens them as you, not as Administrator.
    Windows can start Windows Update again by itself during a long game; the
    post-exit run only starts what this script stopped.
    Scripts have no crash recovery: if the PC or TrayTrigger stops while you
    play, the apps stay closed until you open them. The services come back at
    the next restart, because stopping a service doesn't change how it starts.

  MAKE IT YOURS
    Many apps have their own clean way to quit. OneDrive, for example, quits
    properly with "OneDrive.exe /shutdown". Add a special case in the
    prelaunch section for the apps you care about.
#>
param(
    [string]$Phase,
    [string]$GameName,
    [string]$GameExe,
    [string]$GameId,
    [string]$Playtime,
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$ScriptArgs
)

# ---- Change these ------------------------------------------------------------

# Closed when Script Arguments says "recommended".
$Recommended = @('OneDrive', 'Dropbox', 'GoogleDriveFS', 'Creative Cloud', 'ms-teams', 'Teams', 'slack')

# Run as Administrator: also stop these services for the game, and start them
# again after. wuauserv is Windows Update; DoSvc is Delivery Optimization, which
# downloads updates and shares them with other PCs. $false leaves them alone.
$PauseWindowsUpdate = $true
$UpdateServices = @('wuauserv', 'DoSvc')

# How long apps get to close on their own before they are ended.
$GraceSeconds = 5

# Never closed, even when listed: closing these would break Windows, TrayTrigger
# or the game's own launch.
$NeverClose = @('explorer', 'dwm', 'TrayTrigger', 'steam', 'steamwebhelper',
    'EpicGamesLauncher', 'GalaxyClient', 'EADesktop', 'upc', 'XboxPcApp', 'Battle.net')

# ------------------------------------------------------------------------------

# The notes that carry what was closed and stopped from the pre-launch run to the
# post-exit run. Named after the game ID, so games don't mix up notes.
# Still named QuietMode, which this example used to be called: a game running
# while TrayTrigger updates would otherwise leave its note under the old name,
# and the post-exit run would not find it - so the apps it closed would stay
# closed. The name is never seen; only the two runs of this script read it.
$note = Join-Path $env:TEMP "TrayTrigger-QuietMode-$GameId.txt"
$serviceNote = Join-Path $env:TEMP "TrayTrigger-QuietMode-$GameId-services.txt"

$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)

switch ($Phase) {
    'prelaunch' {
        # Empty does nothing, Windows Update included: nothing is closed or paused until you say
        # what. "recommended" among your names stands for the list above.
        if (-not $ScriptArgs) {
            Write-Output 'Nothing named, so nothing was closed. Put "recommended" or process names in Edit Game > Script Arguments, for example: recommended Spotify'
            exit 0
        }
        $names = @()
        foreach ($arg in $ScriptArgs) {
            if ($arg -eq 'recommended') { $names += $Recommended } else { $names += $arg }
        }

        # Work out what to close first, so the waiting below happens only once.
        $targets = @()
        foreach ($arg in ($names | Select-Object -Unique)) {
            # Accept "OneDrive" and "OneDrive.exe" alike.
            $name = $arg -replace '\.exe$', ''
            if (-not $name) { continue }

            if ($NeverClose -contains $name) {
                Write-Output "Skipping ${name}: it is on the never-close list."
                continue
            }

            $processes = @(Get-Process -Name $name -ErrorAction SilentlyContinue)
            if ($processes.Count -eq 0) {
                Write-Output "$name is not running."
                continue
            }

            # The full path is what we need to start it again later. It is empty
            # for a program running as Administrator, which we can't close anyway.
            $path = ($processes | Where-Object { $_.Path } | Select-Object -First 1).Path
            if (-not $path) {
                Write-Output "Skipping ${name}: it is running as Administrator."
                continue
            }

            $targets += [pscustomobject]@{ Name = $name; Path = $path; Processes = $processes }
        }

        if ($targets.Count -gt 0) {
            # Ask nicely first. CloseMainWindow is the same as clicking the window's X,
            # and returns false for an app with no window.
            $asked = $false
            foreach ($target in $targets) {
                foreach ($process in $target.Processes) {
                    if ($process.CloseMainWindow()) { $asked = $true }
                }
            }
            if ($asked) {
                $targets.Processes | Wait-Process -Timeout $GraceSeconds -ErrorAction SilentlyContinue
            }

            # End whatever is still running, then remember what was closed.
            foreach ($target in $targets) {
                $left = @($target.Processes | Where-Object { -not $_.HasExited })
                if ($left.Count -gt 0) {
                    $left | Stop-Process -Force -ErrorAction SilentlyContinue
                    Write-Output "Ended $($target.Name)."
                }
                else {
                    Write-Output "Closed $($target.Name)."
                }
            }
            Set-Content -LiteralPath $note -Value $targets.Path
        }

        # Windows Update and Delivery Optimization: stopped only as Administrator,
        # and only the ones running, so the post-exit run starts exactly those.
        if ($PauseWindowsUpdate) {
            if (-not $isAdmin) {
                Write-Output 'Windows Update left alone: tick "Run scripts as Administrator" in Edit Game to pause it while you play.'
            }
            else {
                $stopped = @()
                foreach ($serviceName in $UpdateServices) {
                    $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
                    if (-not $service -or $service.Status -ne 'Running') { continue }
                    try {
                        Stop-Service -Name $serviceName -Force -ErrorAction Stop
                        $stopped += $serviceName
                        Write-Output "Paused $($service.DisplayName)."
                    }
                    catch {
                        Write-Output "Couldn't pause $($service.DisplayName): $($_.Exception.Message)"
                    }
                }
                if ($stopped.Count -gt 0) { Set-Content -LiteralPath $serviceNote -Value $stopped }
            }
        }
    }

    'postexit' {
        $hadNote = $false

        if (Test-Path -LiteralPath $note) {
            $hadNote = $true
            $paths = @(Get-Content -LiteralPath $note)
            Remove-Item -LiteralPath $note -Force

            foreach ($path in $paths) {
                $name = [IO.Path]::GetFileNameWithoutExtension($path)

                if (Get-Process -Name $name -ErrorAction SilentlyContinue) {
                    Write-Output "$name is already running again."
                    continue
                }
                # An app can update itself into a new folder while you play.
                if (-not (Test-Path -LiteralPath $path)) {
                    Write-Output "Can't reopen ${name}: $path no longer exists."
                    continue
                }

                if ($isAdmin) {
                    # Started through Explorer, which runs as you: an app reopened from
                    # an Administrator script would otherwise run as Administrator too.
                    Start-Process -FilePath (Join-Path $env:WINDIR 'explorer.exe') -ArgumentList "`"$path`""
                }
                else {
                    Start-Process -FilePath $path -WorkingDirectory (Split-Path -Parent $path)
                }
                Write-Output "Reopened $name."
            }
        }

        if (Test-Path -LiteralPath $serviceNote) {
            $hadNote = $true
            $services = @(Get-Content -LiteralPath $serviceNote)
            if (-not $isAdmin) {
                Write-Output 'Windows Update was paused by an Administrator run, so only one can start it again: tick "Run scripts as Administrator", or restart the PC.'
            }
            else {
                Remove-Item -LiteralPath $serviceNote -Force
                foreach ($serviceName in $services) {
                    $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
                    if (-not $service) { continue }
                    if ($service.Status -eq 'Running') {
                        Write-Output "$($service.DisplayName) is already running again."
                        continue
                    }
                    try {
                        Start-Service -Name $serviceName -ErrorAction Stop
                        Write-Output "Resumed $($service.DisplayName)."
                    }
                    catch {
                        Write-Output "Couldn't resume $($service.DisplayName): $($_.Exception.Message). It starts again at the next restart."
                    }
                }
            }
        }

        if (-not $hadNote) {
            Write-Output 'This script did not close or pause anything. Nothing to reopen.'
        }
    }

    default {
        Write-Output "Unknown phase '$Phase'."
        exit 1
    }
}

exit 0
