<#
  Name:             Close Background Apps
  Description:      Closes background apps, such as cloud sync, before a game and
                    reopens them after.
  Author:           TrayTrigger
  Version:          3.2
  Phase:            both
  Needs admin:      no
  Dependencies:     none
  Script Arguments: "recommended" for the recommended list, and/or process names
                    to close, separated by spaces, and "force" to end any that
                    don't close when asked. In any order. Empty does nothing.

  DO NOT EDIT THIS FILE. It is TrayTrigger's copy, not yours. Every time
  TrayTrigger starts it compares this file with the copy inside it and
  replaces it if they differ, which is how corrections reach you. An edit of
  yours is therefore undone at the very next start, not only when you update
  TrayTrigger. It is not thrown away: your version is renamed alongside, as
  this file's name with ".previous" on the end, and left alone after that.

  To make it yours properly: Edit Game > New script..., or copy this file
  under another name first - a file TrayTrigger did not put here is never
  touched. Settings that vary by PC belong in Edit Game > Script Arguments.

  WHY
    Cloud sync apps keep working in the background: uploading, downloading
    and scanning your files. OneDrive also syncs your Documents folder, where
    many games keep their saves, settings and shader caches, so it gets busy
    exactly when the game writes to them. Closing these for the length of a
    game frees disk, CPU and bandwidth. This script brings back exactly what
    it closed when you are done, and says what it did. It does not "clean"
    memory or score your PC: those do nothing for a game.

  SET IT UP
    1. In Edit Game, choose this file as the pre-launch script and tick "Use
       the same script for pre-launch and post-exit". To use it for every
       game, set it as both default scripts in Settings > Launch &
       Performance instead.
    2. In Script Arguments, type "recommended" to close the recommended list:
         OneDrive, Dropbox and Google Drive
       Or type the process names you want closed instead, for example:
         OneDrive Spotify
       Or both, to close the list and yours:
         recommended Spotify
       With Script Arguments empty the script does nothing at all.
       Find a process name in Task Manager > Details, without ".exe". Put a
       name that contains spaces in double quotes.
    3. Some apps ignore a request to close. They are left running and the
       script says which. Add "force" anywhere in Script Arguments to end
       those instead:
         recommended Spotify force
    4. Press Test next to the pre-launch box: the apps close. Press Test next
       to the post-exit box: they come back.

  OTHERS PEOPLE CLOSE, AND WHY THEY AREN'T ON THE LIST
    Browsers (chrome, msedge, firefox)   can lose tabs or a half-typed form
    Discord (Discord)                    you drop out of voice chat
    Teams, Slack (ms-teams, slack)       you drop out of calls; they use
                                         memory more than CPU or disk
    Name them yourself if that's fine for you.

  STUTTER FROM RGB AND HARDWARE MONITORING SOFTWARE
    Armoury Crate, iCUE, NZXT CAM, Razer Synapse and MSI Center are often
    behind stutter, because they keep reading your PC's sensors. This script
    is the wrong tool for them: the part that reads the sensors usually runs
    as a Windows service, which closing the app doesn't stop, and closing
    them can also stop your lighting, macros or fan curves. If a game
    stutters, turn off their monitoring features or try a game without them.

  HOW IT WORKS
    prelaunch  For each name that is running, remembers the program's full
               path and asks it to close, the way Windows does when you sign
               out. OneDrive is asked with its own "/shutdown" command. After
               a few seconds, anything that closed is noted in your TEMP
               folder. Anything still running is left alone, or ended if
               Script Arguments says "force".
    postexit   Starts each program that was closed again, unless it is
               already running, and deletes the note.

  GOOD TO KNOW
    Without "force", an app that ignores the request keeps running, and is
    not started again after the game since it never closed. With "force", an
    app that is ended loses anything it hadn't saved: that is fine for sync
    apps, which pick up where they left off. Don't list an editor or anything
    else that could be holding unsaved work.
    A program running as Administrator can't be closed from a normal script,
    so it is skipped.
    Restarted apps start the way they do from their exe, which may open their
    window instead of starting in the tray. OneDrive is started in the tray.
    Run as Administrator, the script still reopens them as you.
    With two games running at once, the apps come back when the first one
    exits.
    Scripts have no crash recovery: if the PC or TrayTrigger stops while you
    play, the apps stay closed until you open them.

  MAKE IT YOURS
    Many apps have their own clean way to quit, like OneDrive's "/shutdown".
    Add a special case in the prelaunch section for the apps you care about.
#>
param(
    [string]$Phase,
    [string]$GameName,
    [string]$GameExe,
    [string]$GameId,
    [string]$Playtime,
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$ScriptArgs
)

# ---- Change these ------------------------------------------------------------

# Closed when Script Arguments says "recommended".
$Recommended = @('OneDrive', 'Dropbox', 'GoogleDriveFS')

# How long apps get to close on their own.
$GraceSeconds = 5

# Never closed, even when listed: closing these would break Windows, TrayTrigger
# or the game's own launch.
$NeverClose = @('explorer', 'dwm', 'TrayTrigger', 'steam', 'steamwebhelper',
    'EpicGamesLauncher', 'GalaxyClient', 'EADesktop', 'upc', 'XboxPcApp', 'Battle.net')

# ------------------------------------------------------------------------------

# The note that carries what was closed from the pre-launch run to the post-exit
# run. Named after the game ID, so games don't mix up notes.
# Still named QuietMode, which this example used to be called: a game running
# while TrayTrigger updates would otherwise leave its note under the old name,
# and the post-exit run would not find it - so the apps it closed would stay
# closed. The name is never seen; only the two runs of this script read it.
$note = Join-Path $env:TEMP "TrayTrigger-QuietMode-$GameId.txt"

$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)

switch ($Phase) {
    'prelaunch' {
        # "recommended" stands for the list above and "force" is a switch; every
        # other word is a process name. Empty does nothing: nothing is closed
        # until you say what.
        $force = $false
        $names = @()
        foreach ($arg in $ScriptArgs) {
            if ($arg -eq 'force') { $force = $true }
            elseif ($arg -eq 'recommended') { $names += $Recommended }
            else { $names += $arg }
        }
        if ($names.Count -eq 0) {
            Write-Output 'Nothing named, so nothing was closed. Put "recommended" or process names in Edit Game > Script Arguments, for example: recommended Spotify'
            exit 0
        }

        # Work out what to close first, so the waiting below happens only once.
        $targets = @()
        $skipped = @()
        foreach ($arg in ($names | Select-Object -Unique)) {
            # Accept "OneDrive" and "OneDrive.exe" alike.
            $name = $arg -replace '\.exe$', ''
            if (-not $name) { continue }

            if ($NeverClose -contains $name) {
                Write-Output "Skipping ${name}: it is on the never-close list."
                $skipped += $name
                continue
            }

            $processes = @(Get-Process -Name $name -ErrorAction SilentlyContinue)
            if ($processes.Count -eq 0) {
                Write-Output "$name is not running."
                continue
            }

            # The full path is what we need to start it again later. It is empty
            # for a program running as Administrator, which we can't close anyway.
            $path = ($processes | Where-Object { $_.Path } | Select-Object -First 1).Path
            if (-not $path) {
                Write-Output "Skipping ${name}: it is running as Administrator."
                $skipped += $name
                continue
            }

            $targets += [pscustomobject]@{ Name = $name; Path = $path; Processes = $processes }
        }

        if ($targets.Count -eq 0) {
            # A "TT:" line is for the player: it goes on the game's Played row in
            # Activity & History and into the launch popup. The rest is for the log.
            if ($skipped.Count -gt 0) {
                Write-Output "TT: nothing closed, this script can't close $($skipped -join ', ') (the log says why)"
            }
            else {
                Write-Output 'TT: nothing to close, none of the apps named was running'
            }
            exit 0
        }

        # Ask each one to close. taskkill without /F sends the same close message
        # Windows sends when you sign out, which reaches a tray app's hidden
        # window too. It fails at once for a program with no window at all.
        $taskkill = Join-Path $env:WINDIR 'System32\taskkill.exe'
        $asked = $false
        foreach ($target in $targets) {
            if ($target.Name -eq 'OneDrive') {
                Start-Process -FilePath $target.Path -ArgumentList '/shutdown' -WindowStyle Hidden
                $asked = $true
                continue
            }
            foreach ($process in $target.Processes) {
                & $taskkill /PID $process.Id 2>&1 | Out-Null
                if ($LASTEXITCODE -eq 0) { $asked = $true }
            }
        }
        if ($asked) {
            $targets.Processes | Wait-Process -Timeout $GraceSeconds -ErrorAction SilentlyContinue
        }

        # Note what closed. What didn't is left alone, or ended with "force".
        $closed = @()
        $closedNames = @()
        $leftRunning = @()
        foreach ($target in $targets) {
            $left = @($target.Processes | Where-Object { -not $_.HasExited })
            if ($left.Count -eq 0) {
                Write-Output "Closed $($target.Name)."
                $closed += $target.Path
                $closedNames += $target.Name
            }
            elseif ($force) {
                $left | Stop-Process -Force -ErrorAction SilentlyContinue
                Write-Output "Ended $($target.Name)."
                $closed += $target.Path
                $closedNames += $target.Name
            }
            else {
                Write-Output "$($target.Name) didn't close when asked, so it was left running. Add force to Script Arguments to end it."
                $leftRunning += $target.Name
            }
        }
        if ($closed.Count -gt 0) { Set-Content -LiteralPath $note -Value $closed }

        # One line for the player, on the game's Played row and in the launch popup.
        $summary = @()
        if ($closedNames.Count -gt 0) { $summary += "closed $($closedNames -join ', ')" }
        if ($leftRunning.Count -gt 0) { $summary += "$($leftRunning -join ', ') wouldn't close" }
        Write-Output "TT: $($summary -join '; ')"
    }

    'postexit' {
        if (-not (Test-Path -LiteralPath $note)) {
            Write-Output 'This script did not close anything. Nothing to reopen.'
            Write-Output 'TT: nothing to reopen'
            exit 0
        }
        $paths = @(Get-Content -LiteralPath $note)
        Remove-Item -LiteralPath $note -Force

        $reopened = @()
        $notReopened = @()
        foreach ($path in $paths) {
            $name = [IO.Path]::GetFileNameWithoutExtension($path)

            if (Get-Process -Name $name -ErrorAction SilentlyContinue) {
                Write-Output "$name is already running again."
                $reopened += "$name (already running)"
                continue
            }
            # An app can update itself into a new folder while you play.
            if (-not (Test-Path -LiteralPath $path)) {
                Write-Output "Can't reopen ${name}: $path no longer exists."
                $notReopened += $name
                continue
            }

            try {
                if ($isAdmin) {
                    # Started through Explorer, which runs as you: an app reopened from
                    # an Administrator script would otherwise run as Administrator too.
                    Start-Process -FilePath (Join-Path $env:WINDIR 'explorer.exe') -ArgumentList "`"$path`"" -ErrorAction Stop
                }
                elseif ($name -eq 'OneDrive') {
                    # Back in the tray, not with its folder window open.
                    Start-Process -FilePath $path -ArgumentList '/background' -ErrorAction Stop
                }
                else {
                    Start-Process -FilePath $path -WorkingDirectory (Split-Path -Parent $path) -ErrorAction Stop
                }
                Write-Output "Reopened $name."
                $reopened += $name
            }
            catch {
                Write-Output "Couldn't reopen ${name}: $($_.Exception.Message) Open it yourself from $path"
                $notReopened += $name
            }
        }

        $summary = @()
        if ($reopened.Count -gt 0) { $summary += "reopened $($reopened -join ', ')" }
        if ($notReopened.Count -gt 0) { $summary += "couldn't reopen $($notReopened -join ', ')" }
        Write-Output "TT: $($summary -join '; ')"
    }

    default {
        Write-Output "Unknown phase '$Phase'."
        exit 1
    }
}

exit 0
